###rabbitmq:
###  image: rabbitmq
###  container_name: rabbitmq
###  ports:
###    - "5672:5672"
##rabbitmq:
##  image: rabbitmq:3-management-alpine
##  environment:
##    RABBITMQ_DEFAULT_USER: test
##    RABBITMQ_DEFAULT_PASS: test
##  ports:
##    - "5672:5672"
##    - "15672:15672"
##    - "25672:25672"
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'
volumes:
  rabbitmq-data:
   driver: local
